---

- name: Setup environment to run the sample
  hosts: all
  remote_user: root
  become:      yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

  roles:

    - role: maven

    - role: java
      java:
        version: java8
        apt_repository: ppa:webupd8team/java

    - role: hello-world
